"use client";

import type { FieldConfig, FieldSection } from "@/lib/types";
import ImageField from "@/components/ui/ImageField";
import ImagesField from "@/components/ui/ImagesField";

const SECTION_ORDER: FieldSection[] = [
  "Basic Info",
  "Schedule",
  "Location",
  "Media",
  "Status",
];

type RecordFormProps = {
  fields: FieldConfig[];
  formData: Record<string, unknown>;
  mode: "create" | "edit";
  saving: boolean;
  onFieldChange: (key: string, value: unknown) => void;
  onSave: () => void;
  onCancel: () => void;
  onFetchGooglePlace?: () => void;
  fetchingPlace?: boolean;
};

function formatDisplayValue(value: unknown, field: FieldConfig): string {
  if (value === null || value === undefined) return "";

  if (field.type === "json") {
    return typeof value === "object"
      ? JSON.stringify(value, null, 2)
      : String(value);
  }

  if (field.type === "date" && typeof value === "string") {
    return value.split("T")[0];
  }

  if (field.type === "time" && typeof value === "string") {
    return value.slice(0, 5);
  }

  return String(value);
}

export default function RecordForm({
  fields,
  formData,
  mode,
  saving,
  onFieldChange,
  onSave,
  onCancel,
  onFetchGooglePlace,
  fetchingPlace,
}: RecordFormProps) {
  const visibleFields = fields.filter((field) => {
    if (field.autoGenerated) return mode === "edit";
    return true;
  });

  const hasGooglePlaceId = fields.some((f) => f.key === "google_place_id");

  const sections = SECTION_ORDER.map((section) => ({
    section,
    fields: visibleFields.filter((field) => (field.section ?? "Basic Info") === section),
  })).filter((group) => group.fields.length > 0);

  function renderField(field: FieldConfig) {
    const value = formatDisplayValue(formData[field.key], field);
    const isReadonly = field.type === "readonly" || field.autoGenerated;

    if (field.type === "image" && !isReadonly) {
      return (
        <ImageField
          key={field.key}
          label={field.label}
          required={field.required}
          value={String(formData[field.key] ?? "")}
          onChange={(url) => onFieldChange(field.key, url)}
        />
      );
    }

    if (field.type === "images" && !isReadonly) {
      const images = Array.isArray(formData[field.key])
        ? (formData[field.key] as string[])
        : [];
      return (
        <ImagesField
          key={field.key}
          label={field.label}
          value={images}
          onChange={(urls) => onFieldChange(field.key, urls)}
        />
      );
    }

    return (
      <div key={field.key}>
        <label className="mb-2 block text-sm font-semibold text-slate-700">
          {field.label}
          {field.required && !isReadonly && (
            <span className="ml-1 text-red-500">*</span>
          )}
        </label>

        {field.type === "select" && !isReadonly ? (
          <select
            value={value}
            onChange={(e) => onFieldChange(field.key, e.target.value)}
            className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-blue-600"
          >
            {field.options?.map((option) => (
              <option key={option.value} value={option.value}>
                {option.label}
              </option>
            ))}
          </select>
        ) : field.type === "textarea" && !isReadonly ? (
          <textarea
            value={value}
            onChange={(e) => onFieldChange(field.key, e.target.value)}
            placeholder={field.placeholder}
            rows={3}
            className="w-full resize-y rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-blue-600"
          />
        ) : field.type === "json" && !isReadonly ? (
          <textarea
            value={value}
            onChange={(e) => onFieldChange(field.key, e.target.value)}
            placeholder={field.placeholder}
            rows={4}
            className="w-full resize-y rounded-xl border border-slate-300 bg-white px-4 py-3 font-mono text-sm outline-none focus:border-blue-600"
          />
        ) : isReadonly ? (
          <input
            type="text"
            value={value}
            disabled
            className="w-full rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 text-sm text-slate-400"
          />
        ) : (
          <input
            type={
              field.type === "number"
                ? "number"
                : field.type === "date"
                  ? "date"
                  : field.type === "time"
                    ? "time"
                    : "text"
            }
            value={value}
            onChange={(e) => onFieldChange(field.key, e.target.value)}
            placeholder={field.placeholder}
            step={field.type === "number" ? "any" : undefined}
            className="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none focus:border-blue-600"
          />
        )}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {hasGooglePlaceId && onFetchGooglePlace && (
        <div className="rounded-xl border border-blue-200 bg-blue-50 p-4">
          <p className="text-sm font-semibold text-blue-900">
            Google Places Integration
          </p>
          <p className="mt-1 text-xs text-blue-700">
            Enter a Google Place ID and auto-fill details including images.
          </p>
          <button
            type="button"
            onClick={onFetchGooglePlace}
            disabled={fetchingPlace || !formData.google_place_id}
            className="mt-3 rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white hover:bg-blue-700 disabled:opacity-60"
          >
            {fetchingPlace ? "Fetching..." : "Fetch from Google Places"}
          </button>
        </div>
      )}

      {sections.map(({ section, fields: sectionFields }) => (
        <div key={section}>
          <p className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-400">
            {section}
          </p>
          <div className="space-y-4 rounded-xl border border-slate-100 bg-slate-50/60 p-4">
            {sectionFields.map((field) => renderField(field))}
          </div>
        </div>
      ))}

      <div className="flex gap-3 pt-4">
        <button
          type="button"
          onClick={onSave}
          disabled={saving}
          className="flex-1 rounded-xl bg-green-600 px-5 py-3 text-sm font-bold text-white hover:bg-green-700 disabled:opacity-60"
        >
          {saving
            ? "Saving..."
            : mode === "create"
              ? "Create Record"
              : "Save Changes"}
        </button>

        <button
          type="button"
          onClick={onCancel}
          disabled={saving}
          className="flex-1 rounded-xl bg-slate-700 px-5 py-3 text-sm font-bold text-white hover:bg-slate-800 disabled:opacity-60"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
