import type { FieldConfig, TableKey } from "./types";

const STATUS_OPTIONS = [
  { value: "draft", label: "Draft" },
  { value: "published", label: "Published" },
];

const AUTO_FIELDS: FieldConfig[] = [
  { key: "id", label: "ID", type: "readonly", autoGenerated: true },
  {
    key: "created_at",
    label: "Created At",
    type: "readonly",
    autoGenerated: true,
  },
  {
    key: "updated_at",
    label: "Updated At",
    type: "readonly",
    autoGenerated: true,
  },
];

const RESTAURANT_FIELDS: FieldConfig[] = [
  { key: "name", label: "Name", type: "text", required: true },
  { key: "category", label: "Category", type: "text", placeholder: "e.g. halal_restaurant" },
  { key: "district", label: "District", type: "text", placeholder: "e.g. Kuching" },
  { key: "rating", label: "Rating", type: "number", placeholder: "e.g. 4.2" },
  {
    key: "price_range",
    label: "Price Range",
    type: "select",
    options: [
      { value: "", label: "—" },
      { value: "$", label: "$" },
      { value: "$$", label: "$$" },
      { value: "$$$", label: "$$$" },
    ],
  },
  { key: "short_description", label: "Short Description", type: "textarea" },
  { key: "address", label: "Address", type: "textarea" },
  { key: "latitude", label: "Latitude", type: "number" },
  { key: "longitude", label: "Longitude", type: "number" },
  { key: "image_url", label: "Image", type: "image" },
  {
    key: "menu_images",
    label: "Menu Images",
    type: "images",
    defaultValue: [],
    placeholder: '["https://example.com/image.jpg"]',
  },
  {
    key: "halal_status",
    label: "Halal Status",
    type: "select",
    defaultValue: "unknown",
    options: [
      { value: "unknown", label: "Unknown" },
      { value: "halal", label: "Halal" },
      { value: "non_halal", label: "Non Halal" },
    ],
  },
  { key: "google_place_id", label: "Google Place ID", type: "text" },
  {
    key: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "draft",
    options: STATUS_OPTIONS,
  },
  ...AUTO_FIELDS,
];

const PLACE_FIELDS: FieldConfig[] = [
  { key: "title", label: "Title", type: "text", required: true },
  { key: "category", label: "Category", type: "text", placeholder: "Landmark, Nature, Museum…" },
  { key: "region", label: "Region", type: "text", placeholder: "e.g. kuching" },
  { key: "description", label: "Description", type: "textarea" },
  { key: "address", label: "Address", type: "textarea" },
  { key: "latitude", label: "Latitude", type: "number" },
  { key: "longitude", label: "Longitude", type: "number" },
  { key: "rating", label: "Rating", type: "number" },
  { key: "distance", label: "Distance", type: "text", placeholder: "e.g. 4.5km" },
  { key: "time_away", label: "Time Away", type: "text", placeholder: "e.g. 10 mins away" },
  { key: "image_url", label: "Image", type: "image" },
  { key: "google_place_id", label: "Google Place ID", type: "text" },
  {
    key: "source",
    label: "Source",
    type: "text",
    defaultValue: "google",
  },
  {
    key: "content_type",
    label: "Content Type",
    type: "select",
    defaultValue: "landmark",
    options: [
      { value: "landmark", label: "Landmark" },
      { value: "tour", label: "Tour" },
      { value: "roadtrip", label: "Roadtrip" },
    ],
  },
  { key: "website", label: "Website", type: "text" },
  {
    key: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "draft",
    options: STATUS_OPTIONS,
  },
  ...AUTO_FIELDS,
];

const STAY_FIELDS: FieldConfig[] = [
  { key: "name", label: "Name", type: "text", required: true },
  {
    key: "type",
    label: "Type",
    type: "select",
    defaultValue: "Hotel",
    options: [
      { value: "Hotel", label: "Hotel" },
      { value: "Homestay", label: "Homestay" },
      { value: "Resort", label: "Resort" },
      { value: "Apartment", label: "Apartment" },
      { value: "Glamping", label: "Glamping" },
    ],
  },
  { key: "district", label: "District", type: "text" },
  { key: "rating", label: "Rating", type: "number" },
  { key: "review_count", label: "Review Count", type: "number" },
  { key: "description", label: "Description", type: "textarea" },
  { key: "address", label: "Address", type: "textarea" },
  { key: "latitude", label: "Latitude", type: "number" },
  { key: "longitude", label: "Longitude", type: "number" },
  { key: "image_url", label: "Image", type: "image" },
  { key: "tripadvisor_url", label: "TripAdvisor URL", type: "text" },
  { key: "website", label: "Website", type: "text" },
  {
    key: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "draft",
    options: STATUS_OPTIONS,
  },
  ...AUTO_FIELDS,
];

const TOUR_FIELDS: FieldConfig[] = [
  { key: "name", label: "Name", type: "text", required: true },
  { key: "subtitle", label: "Subtitle", type: "text" },
  {
    key: "type",
    label: "Type",
    type: "select",
    defaultValue: "Tour",
    options: [
      { value: "Tour", label: "Tour" },
      { value: "Boat Cruise", label: "Boat Cruise" },
      { value: "Nature Tour", label: "Nature Tour" },
      { value: "Heritage Walk", label: "Heritage Walk" },
    ],
  },
  { key: "district", label: "District", type: "text" },
  { key: "rating", label: "Rating", type: "number" },
  { key: "review_count", label: "Review Count", type: "number" },
  { key: "description", label: "Description", type: "textarea" },
  { key: "address", label: "Address", type: "textarea" },
  { key: "latitude", label: "Latitude", type: "number" },
  { key: "longitude", label: "Longitude", type: "number" },
  { key: "image_url", label: "Image", type: "image" },
  { key: "tripadvisor_url", label: "TripAdvisor URL", type: "text" },
  { key: "booking_url", label: "Booking URL", type: "text" },
  {
    key: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "draft",
    options: STATUS_OPTIONS,
  },
  ...AUTO_FIELDS,
];

const EVENT_FIELDS: FieldConfig[] = [
  { key: "title", label: "Title", type: "text", required: true },
  { key: "type", label: "Type", type: "text", placeholder: "Festival, Concert, Market…" },
  { key: "district", label: "District", type: "text" },
  { key: "description", label: "Description", type: "textarea" },
  { key: "event_date", label: "Event Date", type: "date" },
  { key: "event_time", label: "Event Time", type: "time" },
  { key: "end_date", label: "End Date", type: "date" },
  { key: "location_name", label: "Location Name", type: "text" },
  { key: "address", label: "Address", type: "textarea" },
  { key: "latitude", label: "Latitude", type: "number" },
  { key: "longitude", label: "Longitude", type: "number" },
  { key: "image_url", label: "Image", type: "image" },
  { key: "registration_url", label: "Registration URL", type: "text" },
  {
    key: "status",
    label: "Status",
    type: "select",
    required: true,
    defaultValue: "draft",
    options: STATUS_OPTIONS,
  },
  ...AUTO_FIELDS,
];

export const TABLE_FIELDS: Record<TableKey, FieldConfig[]> = {
  restaurants: RESTAURANT_FIELDS,
  places: PLACE_FIELDS,
  stays: STAY_FIELDS,
  tours: TOUR_FIELDS,
  events: EVENT_FIELDS,
};

export function getEditableFields(table: TableKey): FieldConfig[] {
  return TABLE_FIELDS[table].filter((field) => !field.autoGenerated);
}

export function getDefaultFormData(table: TableKey): Record<string, unknown> {
  const data: Record<string, unknown> = {};

  for (const field of getEditableFields(table)) {
    if (field.defaultValue !== undefined) {
      data[field.key] = field.defaultValue;
    } else if (field.type === "number") {
      data[field.key] = "";
    } else {
      data[field.key] = "";
    }
  }

  return data;
}

export function preparePayload(
  table: TableKey,
  formData: Record<string, unknown>,
  mode: "create" | "edit"
): Record<string, unknown> {
  const fields = getEditableFields(table);
  const payload: Record<string, unknown> = {};

  for (const field of fields) {
    const value = formData[field.key];

    if (value === "" || value === undefined || value === null) {
      if (mode === "create" && field.defaultValue !== undefined) {
        payload[field.key] = field.defaultValue;
      }
      continue;
    }

    if (field.type === "number") {
      const num = Number(value);
      if (!Number.isNaN(num)) {
        payload[field.key] = num;
      }
      continue;
    }

    if (field.type === "json" || field.type === "images") {
      if (typeof value === "string") {
        try {
          payload[field.key] = JSON.parse(value);
        } catch {
          payload[field.key] = value;
        }
      } else {
        payload[field.key] = value;
      }
      continue;
    }

    payload[field.key] = value;
  }

  return payload;
}

export function getRecordLabel(
  table: TableKey,
  record: Record<string, unknown>
): string {
  const nameKey =
    table === "places" || table === "events" ? "title" : "name";
  const value = record[nameKey];
  return value ? String(value) : `Record #${record.id ?? "?"}`;
}
