export type TableKey =
  | "events"
  | "places"
  | "restaurants"
  | "stays"
  | "tours";

export type DashboardTab = TableKey | "all";

export type RecordItem = {
  id?: string | number;
  [key: string]: unknown;
};

export type FieldType =
  | "text"
  | "textarea"
  | "number"
  | "date"
  | "time"
  | "select"
  | "json"
  | "image"
  | "images"
  | "readonly";

export type FieldSection =
  | "Basic Info"
  | "Schedule"
  | "Location"
  | "Media"
  | "Status";

export type FieldConfig = {
  key: string;
  label: string;
  type: FieldType;
  required?: boolean;
  options?: { value: string; label: string }[];
  defaultValue?: unknown;
  placeholder?: string;
  autoGenerated?: boolean;
  section?: FieldSection;
};

export type EditorMode = "create" | "edit" | null;

export type SortDirection = "asc" | "desc";

export type QueryParams = {
  search?: string;
  status?: string;
  category?: string;
  location?: string;
  sortBy?: string;
  sortDir?: SortDirection;
  page?: number;
  pageSize?: number;
};

export type PaginatedResult = {
  records: RecordItem[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
};

export type TableStats = Record<TableKey, number>;

export type AnalyticsData = {
  statusBreakdown: { label: string; value: number; color: string }[];
  locationBreakdown: { label: string; value: number }[];
  categoryBreakdown: { label: string; value: number }[];
};
